# Generated by Django 5.1.6 on 2025-02-17 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task',
            table='tm_task',
        ),
    ]
